services:
    astra_agents_dev:
        image: ghcr.io/ten-framework/astra_agents_build:0.4.0
        container_name: astra_agents_dev
        platform: linux/amd64
        tty: true
        stdin_open: true
        restart: always
        command: "make run-gd-server"
        ports:
            - "${GRAPH_DESIGNER_SERVER_PORT}:${GRAPH_DESIGNER_SERVER_PORT}"
            - "${SERVER_PORT}:${SERVER_PORT}"
        volumes:
            - ./:/app
            - ${LOG_PATH}:${LOG_PATH}
        working_dir: /app
        env_file:
            - .env
        networks:
            - astra_network
    astra_playground:
        image: ghcr.io/ten-framework/astra_playground:v0.4.0-43-g20dffe8
        container_name: astra_playground
        restart: always
        ports:
            - "3000:3000"
        networks:
            - astra_network
        environment:
            - AGENT_SERVER_URL=http://astra_agents_dev:8080

    # use this when you want to run the playground in local development mode
    # astra_playground_dev:
    #     image: node:20-alpine
    #     container_name: astra_playground_dev
    #     restart: always
    #     command: sh -c "cd /app/playground && npm i && npm run dev" #build && npm run start"
    #     ports:
    #     - "3002:3000"
    #     volumes:
    #     - ./:/app
    ten_graph_designer:
        image: ghcr.io/ten-framework/ten_graph_designer:dde0ff1
        container_name: ten_graph_designer
        restart: always
        ports:
            - "3001:3000"
        networks:
            - astra_network
        environment:
            - TEN_DEV_SERVER_URL=http://astra_agents_dev:49483
networks:
  astra_network:
    driver: bridge