services:
  ten_agent_dev:
    image: ghcr.io/ten-framework/ten_agent_build:0.4.10
    container_name: ten_agent_dev
    platform: linux/amd64
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "${GRAPH_DESIGNER_SERVER_PORT}:${GRAPH_DESIGNER_SERVER_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./:/app
      - ${LOG_PATH}:${LOG_PATH}
    working_dir: /app
    env_file:
      - .env
    networks:
      - ten_agent_network
  ten_agent_playground:
    # image: ghcr.io/ten-framework/ten_agent_playground:0.8.0-80-g5967f0b
    image: ghcr.io/ten-framework/ten_agent_playground:test_03190948
    container_name: ten_agent_playground
    restart: always
    ports:
      - "3000:3000"
    networks:
      - ten_agent_network
    environment:
      - AGENT_SERVER_URL=http://ten_agent_dev:8080
      - TEN_DEV_SERVER_URL=http://ten_agent_dev:49483
  ten_agent_demo:
    image: ghcr.io/ten-framework/ten_agent_demo:0.8.0-34-gfc5b116
    container_name: ten_agent_demo
    restart: always
    ports:
      - "3002:3000"
    networks:
      - ten_agent_network
    environment:
      - AGENT_SERVER_URL=http://ten_agent_dev:8080
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333" # HTTP API 端口
      - "6334:6334" # gRPC API 端口
    volumes:
      - ~/.mem0/qdrant_storage:/qdrant/storage:z
    networks:
      - ten_agent_network
  aibum_playground:
    # image: ghcr.io/ten-framework/ten_agent_playground:0.8.0-80-g5967f0b
    image: ghcr.io/ten-framework/aibum:test_03210123
    container_name: aibum_playground
    restart: always
    ports:
      - "3001:3000"
    networks:
      - ten_agent_network
    environment:
      - AGENT_SERVER_URL=http://ten_agent_dev:8080
  # ten_graph_designer:
  #   image: ghcr.io/ten-framework/ten_graph_designer:4cc33b8
  #   container_name: ten_graph_designer
  #   restart: always
  #   ports:
  #     - "3001:3000"
  #   networks:
  #     - ten_agent_network
  #   environment:
  #     - TEN_DEV_SERVER_URL=http://ten_agent_dev:49483
networks:
  ten_agent_network:
    driver: bridge
